name: Test and Deploy Python Godot Module 
 
on: 
  push: 
    branches: [main] 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
      - uses: actions/checkout@v3 
 
      - name: Set up Python 
        uses: actions/setup-python@v4 
        with: 
          python-version: '3.10' 
 
      - name: Install dependencies 
        run: | 
          pip install pytest build 
 
      - name: Run tests 
        run: pytest 
 
      - name: Build package 
        run: python -m build 
 
      - name: Upload artifact 
        uses: actions/upload-artifact@v3 
        with: 
          name: godot_player_package 
          path: dist/* 
